Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          webcoDevStdoutLogger:
            default:
              class: Neos\Flow\Log\Backend\AnsiConsoleBackend
              options:
                #streamName: 'stdout' # not yet supported
                severityThreshold: '%LOG_DEBUG%'

  Fusion:
    defaultContext:
      Webandco.DevTools: 'Webandco\DevTools\Eel\Helper\WLogHelper'

Webandco:
  DevTools:
    fusion:
      enableRenderStats: false
    nodePublished:
      use: false
      file: '%FLOW_PATH_ROOT%.WebandcoNeosDevToolsLastPublished'
    runtimeStats:
      enabled: false
      includeClasses: []
      excludeClasses:
        # Neos < 9
        - 'TYPO3Fluid\Fluid\Core\Variables\StandardVariableProvider'
        - 'Neos\FluidAdaptor\Core\ViewHelper\TemplateVariableContainer'
        - 'TYPO3Fluid\Fluid\Core\Variables\ChainedVariableProvider'
        - 'TYPO3Fluid\Fluid\Core\Variables\JSONVariableProvider'
        # Neos >= 9
        - 'Neos\Neos\Domain\Model\UserId'
      expression: null
      #expression: 'within(Neos\Neos\Fusion\MenuItemsImplementation) && method(.*->.*())'
      #expression: 'within(Neos\Flow\Mvc\Controller\ControllerInterface) && method(.*->.*Action())'
    log:
      enabled: true
      numberFormat:
        decimals: 4
      sapiLogger: # which logger to use for php sapi types - for possible key values see php_sapi_name()
        #cli: 'webcoDevStdoutLogger' # Log to stdout using AnsiConsoleBackend configured above in case of cli
      callDepth:
        enabled: false
        separator: ' '
        factor: 1
      caller:
        enable: true
        path: false
        class: true
        method: true
        line: true
      pretty: true
      color: true
      colorCallOrder:
        - 'green'
        - 'cyan'
        - 'blue'
        - 'magenta'
        - 'yellow'
        - 'red'
      level: 'debug'
      renderer:
        Webandco\DevTools\Domain\Model\Dto\Stopwatch: Webandco\DevTools\Service\Stopwatch\StopwatchLogRenderer
        Throwable: Webandco\DevTools\Service\Log\ThrowableLogRenderer
        Neos\ContentRepository\Domain\Model\NodeInterface: Webandco\DevTools\Service\Log\NodeInterfaceRenderer
        Neos\ContentRepository\Domain\Model\NodeData: Webandco\DevTools\Service\Log\NodeDataRenderer
        Neos\Fusion\FusionObjects\AbstractFusionObject: Webandco\DevTools\Service\Log\AbstractFusionObjectRenderer
        Neos\Flow\Security\Authorization\Privilege\PrivilegeSubjectInterface: Webandco\DevTools\Service\Log\PrivilegeSubjectInterfaceRenderer
        Neos\ContentRepository\Domain\Model\NodeType: Webandco\DevTools\Service\Log\NodeTypeRenderer
        Neos\Flow\Security\Authorization\Privilege\PrivilegeInterface: Webandco\DevTools\Service\Log\PrivilegeInterfaceRenderer
        Neos\Flow\Aop\JoinPointInterface: Webandco\DevTools\Service\Log\JoinPointInterfaceRenderer
      signal:
        enabled: false
        # regex for signalClassName::signalName
        regex: '/.*/'
      controller:
        enabled: false
        # regex for controllerClassName::actionMethodName
        regex: '/.*/'
      hexDump:
        highlightBinary: 'invert'
        lineSeparator: "\n"
        # 48 chars is nice for large screens, 16 might be better for narrower console output
        bytesPerLine: 48
        # use paddingCharacter for binary data
        paddingCharacter: '.'
        logArray: false
    stopwatch:
      emitSignals: false
      tree:
        wireSignals: false
        enabled: false
    backtrace:
      limit: 50
