Neos:
  Flow:
    log:
      psr3:
        'Neos\Flow\Log\PsrLoggerFactory':
          webcoDevStdoutLogger:
            default:
              class: Neos\Flow\Log\Backend\AnsiConsoleBackend
              options:
                #streamName: 'stdout' # not yet supported
                severityThreshold: '%LOG_DEBUG%'

  Fusion:
    defaultContext:
      Webandco.DevTools: 'Webandco\DevTools\Eel\Helper\WLogHelper'

Webandco:
  DevTools:
    fusion:
      enableRenderStats: false
    nodePublished:
      use: false
      file: '%FLOW_PATH_ROOT%.WebandcoNeosDevToolsLastPublished'
    log:
      enabled: true
      numberFormat:
        decimals: 4
      sapiLogger: # which logger to use for php sapi types - for possible key values see php_sapi_name()
        #cli: 'webcoDevStdoutLogger' # Log to stdout using AnsiConsoleBackend configured above in case of cli
      callDepth:
        enabled: false
        separator: ' '
        factor: 1
      caller: false
      pretty: true
      color: true
      colorCallOrder:
        - 'green'
        - 'cyan'
        - 'blue'
        - 'magenta'
        - 'yellow'
        - 'red'
      level: 'debug'
      renderer:
        Webandco\DevTools\Domain\Model\Dto\Stopwatch: Webandco\DevTools\Service\Stopwatch\StopwatchLogRenderer
        Throwable: Webandco\DevTools\Service\Log\ThrowableLogRenderer
        Neos\ContentRepository\Domain\Model\NodeInterface: Webandco\DevTools\Service\Log\NodeInterfaceRenderer
        Neos\ContentRepository\Domain\Model\NodeData: Webandco\DevTools\Service\Log\NodeDataRenderer
        Neos\Fusion\FusionObjects\AbstractFusionObject: Webandco\DevTools\Service\Log\AbstractFusionObjectRenderer
      signal:
        enabled: false
        # regex for signalClassName::signalName
        regex: '/.*/'
      controller:
        enabled: false
        # regex for controllerClassName::actionMethodName
        regex: '/.*/'
    stopwatch:
      emitSignals: false
      tree:
        wireSignals: false
        enabled: false
    backtrace:
      limit: 50
