Webandco:
  DevTools:
    nodePublished:
      use: false
      file: '%FLOW_PATH_ROOT%.WebandcoNeosDevToolsLastPublished'
    log:
      enabled: false
      caller: false
      pretty: true
      color: true
      level: 'debug'
      renderer:
        Webandco\DevTools\Domain\Model\Dto\Stopwatch: Webandco\DevTools\Service\Stopwatch\StopwatchLogRenderer
        Throwable: Webandco\DevTools\Service\Log\ThrowableLogRenderer
    stopwatch:
      emitSignals: false
      tree:
        wireSignals: false
        enabled: false
    backtrace:
      limit: 50
